/**/yolo_orientation:
  ros__parameters:
    active_camera: "ffc"  # Change to "dfc" or "ffc" to switch cameras

    # ---------- FFC configuration ----------
    ffc_model: "ffc_rs_26.pt"
    ffc_class_id_map: "{
      0: 'blood',
      1: 'buoy',
      2: 'compass',
      3: 'circle',
      4: 'fire',
      5: 'hammer_and_wrench',
      6: 'slalom',
      7: 'sos'
    }"
    ffc_threshold: 0.75
    ffc_iou: 0.9

    # ---------- DFC configuration ----------
    dfc_model: "dfc_rs_26.pt"
    dfc_class_id_map: "{
      0: 'bandage',
      1: 'blood',
      2: 'fire',
      3: 'helmet',
      4: 'nut_and_bolt',
      5: 'pill',
      6: 'plug',
      7: 'warning'
    }"

    dfc_threshold: 0.75
    dfc_iou: 0.9

# Full map from CVAT for reference
    # dfc_class_id_map: "{
    #   0: 'ambulance',
    #   1: 'bandage',
    #   2: 'blood',
    #   3: 'buoy',
    #   4: 'compass',
    #   5: 'circle',
    #   6: 'fire',
    #   7: 'fire_engine',
    #   8: 'hammer_and_wrench',
    #   9: 'helmet',
    #   10: 'nut_and_bolt',
    #   11: 'pill',
    #   12: 'plug',
    #   13: 'slalom',
    #   14: 'sos',
    #   15: 'warning'
    # }"