/**/yolo_orientation:
  ros__parameters:
    yolo_model: "robosub_2024_5.pt"
    class_id_map: "{
      0: 'buoy', 
      1: 'mapping_map', 
      2: 'mapping_hole', 
      3: 'gate_hot', 
      4: 'bin_temperature'
    }"
    threshold: 0.8
    iou: 0.9
