/**/yolo_orientation:
  ros__parameters:
    active_camera: "ffc"  # Change to "dfc or ffc" to switch cameras
    
    # FFC configuration
    ffc_model: "robosub_2024_v3.pt"
    ffc_class_id_map: "{
      0: 'buoy', 
      1: 'mapping_map', 
      2: 'mapping_hole', 
      3: 'gate_hot', 
      4: 'gate_cold',
      5: 'bin_temperature',
      6: 'bin'
    }"
    ffc_threshold: 0.9
    ffc_iou: 0.9
    
    # DFC configuration
    dfc_model: "just_bin_temp.pt"
    dfc_class_id_map: "{
      0: 'bin_target'
    }"
    dfc_threshold: 0.8
    dfc_iou: 0.9