/**/yolo_orientation:
  ros__parameters:
    active_camera: "ffc"  # Change to "dfc" or "ffc" to switch cameras

    # ---------- FFC configuration ----------
    ffc_model: "SSFB_Table_Augmented2.pt"
    ffc_class_id_map: "{
      0: 'Bin',
      1: 'Bin_saw',
      2: 'Bin_shark',
      3: 'Torpdo_shark_top',
      4: 'Torpedo_saw_top',
      5: 'bin_pink',
      6: 'bin_yellow',
      7: 'bottle_pink',
      8: 'bottle_yellow',
      9: 'gate_saw',
      10: 'gate_shark',
      11: 'spoon_pink',
      12: 'spoon_yellow',
      13: 'torpedo_hole'
    }"
    ffc_threshold: 0.85
    ffc_iou: 0.9

    # ---------- DFC configuration ----------
    dfc_model: "just_bin_temp.pt"
    dfc_class_id_map: "{
      0: 'Bin',
      1: 'Bin_saw',
      2: 'Bin_shark',
      3: 'Torpdo_shark_top',
      4: 'Torpedo_saw_top',
      5: 'bin_pink',
      6: 'bin_yellow',
      7: 'bottle_pink',
      8: 'bottle_yellow',
      9: 'gate_saw',
      10: 'gate_shark',
      11: 'spoon_pink',
      12: 'spoon_yellow',
      13: 'torpedo_hole'
    }"
    dfc_threshold: 0.8
    dfc_iou: 0.9