/**/yolo_orientation:
  ros__parameters:
    active_camera: "ffc"  # Change to "dfc" or "ffc" to switch cameras

    torp_top: "shark"
    bin_target: "bin_saw"

    # ---------- FFC configuration ----------
    # ffc_model: "robosub_2024_v3.pt"
    # ffc_class_id_map: "{
    #   0: 'buoy', 
    #   1: 'gate_sawfish', 
    #   2: 'mapping_hole', 
    #   3: 'gate_reefshark', 
    #   4: 'gate_cold',
    #   5: 'bin_temperature',
    #   6: 'bin'
    # }"
    
    # ffc_model: "rs25.pt"
    # ffc_model: "rs25_8_10_1.pt"
    # ffc_class_id_map: "{
    #   0: 'buoy', 
    #   1: 'mapping_map', 
    #   2: 'mapping_hole', 
    #   3: 'gate_reefshark', 
    #   4: 'gate_cold',
    #   5: 'bin_temperature',
    #   6: 'bin'
    # }"

    #ffc_model: "rs25.pt"
    ffc_model: "rs25_8_15_2.pt"
    ffc_class_id_map: "{
      0: 'bin',
      1: 'bin_saw',
      2: 'bin_shark',
      3: 'torpedo_shark_top',
      4: 'torpedo_saw_top',
      5: 'bin_pink',
      6: 'bin_yellow',
      7: 'bottle_yellow',
      8: 'gate_saw',
      9: 'gate_shark',
      10: 'slalom_red',
      11: 'spoon_pink',
      12: 'torpedo_hole'
    }"
    ffc_threshold: 0.75
    ffc_iou: 0.9

    # ---------- DFC configuration ----------
    dfc_model: "rs25_8_16_dfc.pt"
    dfc_class_id_map: "{
      0: 'Bin',
      1: 'bin_target',
      2: 'Bin_shark',
      3: 'Torpdo_shark_top',
      4: 'Torpedo_saw_top',
      5: 'bin_pink',
      6: 'bin_yellow',
      7: 'bottle_pink',
      8: 'bottle_yellow',
      9: 'gate_saw',
      10: 'gate_shark',
      11: 'spoon_pink',
      12: 'spoon_yellow',
      13: 'torpedo_hole'
    }"
    dfc_threshold: 0.6
    dfc_iou: 0.9
