/tempest/riptide_mapping2:
  ros__parameters:
    init_data:
      binBarrel:
        covar:
          x: 1.0
          y: 1.0
          yaw: 1.0
          z: 1.0
        pose:
          x: 0.0
          y: 0.0
          yaw: 0.0
          z: 1.0
      binPhone:
        covar:
          x: 1.0
          y: 1.0
          yaw: 1.0
          z: 1.0
        pose:
          x: 0.0
          y: 2.0
          yaw: 0.0
          z: 1.0
      TommyGun:
        covar:
          x: 2.0099095090803996e-06
          y: 7.273919994657607e-07
          yaw: 2.2062454055223684e-05
          z: 2.372778249389679e-06
        pose:
          x: -0.5
          y: 1.0
          yaw: 0.0
          z: 1.0
      gman:
        covar:
          x: 10.0 #2.0099095090803996e-06
          y: 10.0 #7.273919994657607e-07
          yaw: 10.0 #2.2062454055223684e-05
          z: 10.0 #2.372778249389679e-06
        pose:
          x: 1.5
          y: 1.0
          yaw: 0.0
          z: 1.0
      bootlegger:
        covar:
          x: 1.0 #2.0099095090803996e-06
          y: 1.0 #7.273919994657607e-07
          yaw: 1.0 #2.2062454055223684e-05
          z: 1.0 #2.372778249389679e-06
        pose:
          x: 1.0
          y: 0.0
          yaw: 0.0
          z: 1.0
      badge:
        covar:
          x: 50.0 #2.0099095090803996e-06
          y: 50.0 #7.273919994657607e-07
          yaw: 50.0 #2.2062454055223684e-05
          z: 50.0 #2.372778249389679e-06
        pose:
          x: 0.0
          y: 0.0
          yaw: 0.0
          z: 1.0
      axe:
        covar:
          x: 1.0
          y: 1.0
          yaw: 1.0
          z: 1.0
        pose:
          x: 0.0
          y: 14.0
          yaw: 0.0
          z: 1.0
      torpedoGman:
        covar:
          x: 1.0 #2.0099095090803996e-06
          y: 1.0 #7.273919994657607e-07
          yaw: 1.0 #2.2062454055223684e-05
          z: 1.0 #2.372778249389679e-06
        pose:
          x: 0.0
          y: 16.0
          yaw: 0.0
          z: 1.0
      torpedoBootlegger:
        covar:
          x: 1.0 #2.0099095090803996e-06
          y: 1.0 #7.273919994657607e-07
          yaw: 1.0 #2.2062454055223684e-05
          z: 1.0 #2.372778249389679e-06
        pose:
          x: 0.0
          y: 18.0
          yaw: 0.0
          z: 1.0
      cash:
        covar:
          x: 1.0 #2.0099095090803996e-06
          y: 1.0 #7.273919994657607e-07
          yaw: 1.0 #2.2062454055223684e-05
          z: 1.0 #2.372778249389679e-06
        pose:
          x: 0.0
          y: 20.0
          yaw: 0.0
          z: 1.0
    # Covariance filter parameters
    cov_limit: 0.01 # Minimum value for the covariance matrix elements
    k_value: 0.01   # Covariance step size (< 1.0) applied per detection

    # relative position filter parameters
    angle_cutoff: 15.0
    distance_limit: 10.0
    confidence_cutoff: .7
        
  
