#
# riptide_mapping configuration file.
#


# BOTH-ROBOTS SETTTINGS
/**/riptide_mapping2:
  ros__parameters:
    # Covariance filter parameters
    cov_limit: 0.01 # Minimum value for the covariance matrix elements
    k_value: 0.1 # Covariance step size (< 1.0) applied per detection
    detection_cov_factor: 7.0

    # relative position filter parameters
    angle_cutoff: 15.0
    distance_limit: 10.0
    confidence_cutoff: 0.2

    # location tracking settings NOTE: buffer size is a per-robot setting.
    
    quantile: [0.01, 0.99]
    minimum_distance: 1.0

# TALOS SETTINGS
/talos/riptide_mapping2:
  ros__parameters:
    init_data:
      gate:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: 3.0
          y: -0.0
          z: -0.25
          yaw: 3.0
      gate_reefshark:
        parent: gate_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: 0.0
          y: 0.25
          z: 0.0
          yaw: 180.0
      gate_sawfish:
        parent: gate_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: 0.0
          y: -0.25
          z: 0.0
          yaw: 180.0
      
      slalom_front:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: -2.0
          y: 0.0
          z: -1.0
          yaw: 0.0
      slalom_middle:
        parent: slalom_front_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: -90.0
        pose:
          x: -3.0
          y: 1.0
          z: -1.0
          yaw: 0.0
      slalom_back:
        parent: slalom_middle_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: -4.0
          y: 0.0
          z: -1.0
          yaw: 0.0
      slalom_close:
        parent: slalom_front_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: 0.0
          y: 0.0
          z: 0.0
          yaw: 0.0
      torpedo:
        parent: map
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 0.5
        pose:
          x: -1.0
          y: 1.0
          z: -1.6
          yaw: 0.0
      torpedo_shark_hole:
        parent: torpedo_frame
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 0.5
        pose:
          x: 0.0
          y: 0.25
          z: 0.25
          yaw: 0.0
      torpedo_sawfish_hole:
        parent: torpedo_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.0
          y: -0.25
          z: -0.25
          yaw: 0.0
      bin_target:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.0
          y: 0.0
          z: -2.1
          yaw: 0.0
      
      # table locations
      table:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 10.0
          y: 4.0
          z: -1.5
          yaw: 0.0
      table_reefshark:
        parent: table_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 1.0
          y: 0.0
          z: 1.0
          yaw: 180.0
      table_sawfish:
        parent: table_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: -1.0
          y: 0.0
          z: 1.0
          yaw: 180.0      
      table_basket_pink:
        parent: table_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.305
          y: 0.0
          z: 0.0
          yaw: 0.0
      table_basket_yellow:
        parent: table_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: -0.305
          y: 0.0
          z: 0.0
          yaw: 0.0
      table_spoon_pink:
        parent: table_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.1
          y: -0.036
          z: 0.0
          yaw: 0.0
      table_bottle_yellow:
        parent: table_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.25
          y: 0.25
          z: 0.0
          yaw: 0.0

      prequal_gate:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 4.0
          y: 0.0
          z: -1.5
          yaw: 180.0
      prequal_pole:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 14.0
          y: 0.0
          z: -1.5
          yaw: 180.0

    # location tracking settings
    buffer_size: 60

# LILTANK SETTINGS
/liltank/riptide_mapping2:
  ros__parameters:
    init_data:
      # table locations
      table:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.0
          y: 0.0
          z: -2.0
          yaw: 0.0
      table_reefshark:
        parent: table_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 1.0
          y: 0.0
          z: 1.0
          yaw: 180.0
      table_sawfish:
        parent: table_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: -1.0
          y: 0.0
          z: 1.0
          yaw: 180.0      
      table_basket_pink:
        parent: table_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.4
          y: 0.0
          z: 0.1
          yaw: 0.0
      table_basket_yellow:
        parent: table_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: -0.4
          y: 0.0
          z: 0.1
          yaw: 0.0
      table_spoon_pink:
        parent: table_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.1
          y: -0.036
          z: 0.0
          yaw: 0.0
      table_bottle_yellow:
        parent: table_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.25
          y: 0.25
          z: 0.0
          yaw: 0.0
    
    # location tracking settings
    buffer_size: 30
