/**/riptide_mapping2:
  ros__parameters:
    init_data:
      gate:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: 6.0
          y: -1.0
          z: -1.0
          yaw: 180.0
      gate_hot:
        parent: gate_frame
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 0.0
        pose:
          x: 0.0
          y: -0.4
          z: 0.0
          yaw: 0.0
      gate_cold:
        parent: gate_frame
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 70.0
        pose:
          x: 0.0
          y: 0.4
          z: 0.0
          yaw: 0.0
      buoy:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: -90.0
        pose:
          x: 14
          y: 2.5
          z: -1.0
          yaw: 180
      torpedo:
        parent: map
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 0.5
        pose:
          x: 19.0
          y: 2.7
          z: -1.0
          yaw: -145.0
      torpedo_large_hole:
        parent: torpedo_frame
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 0.5
        pose:
          x: 0.0
          y: 0.25
          z: 0.25
          yaw: 0.0
      torpedo_small_hole:
        parent: torpedo_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 0.0
          y: -0.25
          z: -0.25
          yaw: 0.0
      bin:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 20
          y: -4.17
          z: -1.5
          yaw: 0.0
      table:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 24.0
          y: 1.85
          z: -1.5
          yaw: 0.0
      prequal_gate:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 4.0
          y: 0.0
          z: -1.5
          yaw: 180.0
      prequal_pole:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 14.0
          y: 0.0
          z: -1.5
          yaw: 180.0
    # Covariance filter parameters
    cov_limit: 0.01 # Minimum value for the covariance matrix elements
    k_value: 0.1 # Covariance step size (< 1.0) applied per detection
    detection_cov_factor: 7.0

    # relative position filter parameters
    angle_cutoff: 15.0
    distance_limit: 10.0
    confidence_cutoff: 0.7

    # Size of buffer for location tracking
    buffer_size: 100
    quantile: [0.01, 0.99]
    minimum_distance: 1.0
