/**/riptide_mapping2:
  ros__parameters:
    init_data:
      gate:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: 4.0
          y: -0.0
          z: -0.25
          yaw: 180.0
      gate_hot:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: 4.0
          y: -0.0
          z: -0.25
          yaw: 180.0
      gate_cold:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: 4.0
          y: 0.0
          z: -0.25
          yaw: 180.0
      slalom_front:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: 0.0
          y: 0.0
          z: -1.0
          yaw: 0.0
      slalom_middle:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: -2.0
          y: 0.0
          z: -1.0
          yaw: 0.0
      slalom_back:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: -4.0
          y: 0.0
          z: -1.0
          yaw: 0.0
      buoy:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: -90.0
        pose:
          x: 6.5
          y: 0.0
          z: -1.0
          yaw: 180.0
      torpedo:
        parent: map
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 0.5
        pose:
          x: -2.0
          y: 0.0
          z: -1.5
          yaw: 0.0
      torpedo_large_hole:
        parent: map
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 0.5
        pose:
          x: -2.0
          y: -0.0
          z: -1.5
          yaw: 0.0
      torpedo_small_hole:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: -2.0
          y: -0.0
          z: -1.5
          yaw: 0.0
      bin_target:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: -0.0
          y: 2.0
          z: -2.1
          yaw: 0.0
      # bin_target:
      #   parent: map
      #   covar:
      #     x: 0.001
      #     y: 0.001
      #     z: 0.001
      #     yaw: 0.001
      #   pose:
      #     x: 0.0
      #     y: 0.0
      #     z: -2.1
      #     yaw: 0.0
      table:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 12.74
          y: -1.72
          z: -1.0
          yaw: 0.0
      bin_pink:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 1.74
          y: -1.72
          z: -1.0
          yaw: 0.0
      bin_yellow:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 1.84
          y: -1.72
          z: -1.0
          yaw: 0.0
      prequal_gate:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 4.0
          y: 0.0
          z: -1.5
          yaw: 180.0
      prequal_pole:
        parent: map
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 14.0
          y: 0.0
          z: -1.5
          yaw: 180.0
    # Covariance filter parameters
    cov_limit: 0.01 # Minimum value for the covariance matrix elements
    k_value: 0.1 # Covariance step size (< 1.0) applied per detection
    detection_cov_factor: 7.0

    # relative position filter parameters
    angle_cutoff: 15.0
    distance_limit: 10.0
    confidence_cutoff: 0.2

    # Size of buffer for location tracking
    buffer_size: 30
    quantile: [0.01, 0.99]
    minimum_distance: 1.0
