/**/riptide_mapping2:
  ros__parameters:
    init_data:
      gate:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 50.0
        pose:
          x: 5.0
          y: 0.0
          z: -1.5
          yaw: 180.0
      earth_glyph:
        parent: gate_frame
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 70.0
        pose:
          x: -0.4
          y: 0.0
          z: 0.0
          yaw: 0.0
      buoy:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 100.0
        pose:
          x: 7.0
          y: -4.0
          z: -1.5
          yaw: 90.0
      buoy_glyph_1:
        parent: buoy_frame
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 100.0
        pose:
          x: 0.0
          y: -0.1875
          z: -0.1875
          yaw: 0.0
      buoy_glyph_2:
        parent: buoy_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 100.0
        pose:
          x: 0.0
          y: 0.1875
          z: 0.1875
          yaw: 0.0
      buoy_glyph_3:
        parent: buoy_frame
        covar:
          x: 0.5
          y: 0.5
          z: 0.5
          yaw: 100.0
        pose:
          x: 0.0
          y: -0.1875
          z: -0.1875
          yaw: 0.0
      buoy_glyph_4:
        parent: buoy_frame
        covar:
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 100.0
        pose:
          x: 0.0
          y: 0.1875
          z: 0.1875
          yaw: 0.0
      torpedo:
        parent: map
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 1.0
        pose:
          x: 4.0
          y: 3.0
          z: -1.0
          yaw: 90.0
      torpedo_upper_hole:
        parent: torpedo_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 1.0
        pose:
          x: 0.0
          y: 0.0
          z: 0.25
          yaw: 0.0
      torpedo_lower_hole:
        parent: torpedo_frame
        covar:
          x: 1.0
          y: 1.0
          z: 1.0
          yaw: 1.0
        pose:
          x: 0.0
          y: 0.0
          z: -0.25
          yaw: 0.0
      table:
        parent: map
        covar:  
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 8.0
          y: -8.0
          z: -1.5
          yaw: 0.0
      prequal_gate:
        parent: map
        covar:  
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 4.0
          y: 0.0
          z: -1.5
          yaw: 180.0
      prequal_pole:
        parent: map
        covar:  
          x: 0.001
          y: 0.001
          z: 0.001
          yaw: 0.001
        pose:
          x: 14.0
          y: 0.0
          z: -1.5
          yaw: 180.0
    # Covariance filter parameters
    cov_limit: 0.01 # Minimum value for the covariance matrix elements
    k_value: 0.1   # Covariance step size (< 1.0) applied per detection
    detection_cov_factor: 7.0

    # relative position filter parameters
    angle_cutoff: 15.0
    distance_limit: 10.0
    confidence_cutoff: 0.7
    
    # Size of buffer for location tracking
    buffer_size: 200
    quantile: [0.01, 0.99]
    minimum_distance: 1.0