/**/dummydetections:
  ros__parameters:
    timer_period: 0.05
    objects:
      # Gate
      - gate
      - gate_repair
      - gate_rescue

      # Slalom
      - slalom_front
      - slalom_middle
      - slalom_back

      # Torpedo
      - torpedo
      - torpedo_blood_hole_large
      - torpedo_blood_hole_small
      - torpedo_fire_hole_large
      - torpedo_fire_hole_small

      # Bin
      - bin
      - bin_target
      - bin_vinyl1
      - bin_vinyl2
      - bin_vinyl3
      - bin_vinyl4
      - bin_magnet_1
      - bin_magnet_2

      # Table/Octagon
      - table
      - table_helmet
      - table_warning
      - table_pill
      - table_plug
      - table_nut_and_bolt
      - table_bandage
      - table_compass
      - table_sos
      - table_buoy
      - table_hammer_and_wrench

    detection_data:
      # Gate
      gate:
        publish: false
        parent: map
        pose: [-2.9, 0.0, -0.6, 0.0, 0.0, 0.0]
        noise: 0.001
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5 #meters. if simulate_pool is true, object will not be published if the robot is closer to the object than this value
        max_dist: 4.5 #meters. if simulate_pool is true, object will not be published if the robot is farther from the object than this value
      gate_repair:
        parent: gate
        pose: [0.0, 0.75, 0.0, 0.0, 0.0, 0.0]
        noise: 0.001
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.25
        max_dist: 3.5
      gate_rescue:
        parent: gate
        pose: [0.0, -0.75, 0.0, 0.0, 0.0, 0.0]
        noise: 0.001
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.25
        max_dist: 3.5

      # Slalom
      slalom_front:
        class: slalom_front
        pose: [-7.2, 0.34, -1.0, 0.0, 0.0, 0.0]
        noise: 0.1
        score: 0.8
        downward: false
        pub_invalid_orientation: true
        min_dist: 0.5
        max_dist: 3.0
      slalom_middle:
        pose: [-9.0, 1.4, -1.0, 0.0, 0.0, 0.0]
        noise: 0.1
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      slalom_back:
        pose: [-11.5, 0.0, -1.0, 0.0, 0.0, 0.0]
        noise: 0.1
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0

      # Torpedo
      torpedo:
        parent: map
        pose: [-16.9, -3.5, -0.6, 0.0, 0.0, 0.0]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 1.0
        max_dist: 3.5
      torpedo_blood_hole_large:
        parent: torpedo
        class_id: blood_hole_large
        pose: [0.2, 0.2, 0.0, 0.0, 0.0, 0.0]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      torpedo_blood_hole_small:
        parent: torpedo
        class_id: blood_hole_small
        pose: [0.2, -0.2, 0.0, 0.0, 0.0, 0.0]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      torpedo_fire_hole_large:
        parent: torpedo
        class_id: fire_hole_large
        pose: [-0.2, 0.2, 0.0, 0.0, 0.0, 0.0]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      torpedo_fire_hole_small:
        parent: torpedo
        class_id: fire_hole_small
        pose: [-0.2, 0.2, 0.0, 0.0, 0.0, 0.0]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0

      # Bin
      # Begin bin CAD shenanigans
      bin: # Not published, just here to move entire prop+children
        publish: false
        parent: map
        pose: [-13.4, 5.3, -2.3, 0.0, 0.0, 3.14]
      bin_vinyl1:
        class_id: fire
        parent: bin
        pose: [0.47372, -0.12206, 0.30103, 0.0, 0.0, 0.0]
        noise: 0.05
        score: 0.8
        downward: true
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      bin_vinyl2:
        class_id: blood
        parent: bin
        pose: [0.23686, 0.34660, 0.33489, 0.0, 0.0, 0.0]
        noise: 0.05
        score: 0.8
        downward: true
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      bin_vinyl3:
        class_id: blood
        parent: bin
        pose: [-0.21663, -0.34660, 0.47036, 0.0, 0.0, 0.0]
        noise: 0.05
        score: 0.8
        downward: true
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      bin_vinyl4:
        class_id: fire
        parent: bin
        pose: [-0.43325, 0.12206, 0.57196, 0.0, 0.0, 0.0]
        noise: 0.05
        score: 0.8
        downward: true
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      bin_magnet_1:
        class_id: magnet
        parent: bin
        pose: [0.76512, 0.37018, 0.15975, 0.0, 0.0, 0.0]
        noise: 0.05
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      bin_magnet_2:
        class_id: magnet
        parent: bin
        pose: [-0.70442, -0.37018, 0.56615, 0.0, 0.0, 3.1415]
        noise: 0.05
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      # End bin CAD shenanigans

      # table is the anchor, its children are offsets
      table:
        parent: map
        pose: [6.0, -4.0, -1.25, 0.0, 0.0, 3.1415]
        noise: 0.05
        score: 0.8
        downward: true
        pub_invalid_orientation: false
        min_dist: 1.0
        max_dist: 4.0
      table_helmet:
        class_id: helmet
        parent: table
        pose: [0.40168, 0.0, 0.021457, 0.0, 0.0, 0.0]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.12
        max_dist: 3.0
      table_warning:
        class_id: warning
        parent: table
        pose: [-0.40168, 0.0, 0.021457, 0.0, 0.0, 0.0]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.12
        max_dist: 3.0
      table_pill:
        class_id: pill
        parent: table
        pose: [-0.25, 0.25, 0.0, 0.0, 0.0, 3.1415]
        noise: 0.05
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.01
        max_dist: 4.0
      table_plug:
        class_id: plug
        parent: table
        pose: [0.25, -0.25, 0.0, 0.0, 0.0, 0.0]
        noise: 0.05
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.01
        max_dist: 4.0
      table_nut_and_bolt:
        class_id: nut_and_bolt
        parent: table
        pose: [0.25, 0.25, 0.0, 0.0, 0.0, 0.0]
        noise: 0.05
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.01
        max_dist: 4.0
      table_bandage:
        class_id: bandage
        parent: table
        pose: [-0.25, -0.25, 0.0, 0.0, 0.0, 3.1415]
        noise: 0.05
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.01
        max_dist: 4.0
      table_compass:
        class_id: compass
        parent: table
        pose: [1.2, 0.0, 1.0, 0.0, 0.0, 3.1415]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      table_hammer_and_wrench:
        class_id: hammer_and_wrench
        parent: table
        pose: [-1.2, 0.0, 1.0, 0.0, 0.0, 0.0]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      table_buoy:
        class_id: buoy
        parent: table
        pose: [0.0, 1.2, 1.0, 0.0, 0.0, 4.71239]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      table_sos:
        class_id: sos
        parent: table
        pose: [0.0, -1.2, 1.0, 0.0, 0.0, 1.5708]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0

/talos/dummydetections:
  ros__parameters:
    #POOL SIMULATION SETTINGS
    simulate_pool: true #if true, will monitor robot's odometry and only publish a detection for an object if the robot is looking at it
    
    #the following settings are only used when simulate_pool is TRUE
    forward_camera_frame: <robot>/base_link #if <robot> is present in name, it will be populated with the robot name
    forward_camera_pub_frame: <robot>/base_link # this is the frame that the detections are published in
    forward_camera_hfov: 120 #degrees. used to determine if robot is actually looking at the object.
    forward_camera_vfov: 68 #degrees. used just like the hfov but not horizontal
    
    downward_camera_frame: <robot>/dfc_camera_link #if <robot> is present in name, it will be populated with the robot name
    downward_camera_pub_frame: <robot>/dfc_camera_link
    downward_camera_hfov: 60
    downward_camera_vfov: 40

/liltank/dummydetections:
  ros__parameters:
    #POOL SIMULATION SETTINGS
    simulate_pool: true #if true, will monitor robot's odometry and only publish a detection for an object if the robot is looking at it
    
    #the following settings are only used when simulate_pool is TRUE
    forward_camera_frame: simulator/<robot>/zed2i/left_optical #if <robot> is present in name, it will be populated with the robot name
    forward_camera_pub_frame: <robot>/base_link # this is the frame that the detections are published in
    forward_camera_hfov: 60 #degrees. used to determine if robot is actually looking at the object.
    forward_camera_vfov: 120 #degrees. used just like the hfov but not horizontal
    
    downward_camera_frame: <robot>/dummy_dfc_link #if <robot> is present in name, it will be populated with the robot name
    downward_camera_pub_frame: <robot>/base_link
    downward_camera_hfov: 60
    downward_camera_vfov: 40
  
