/tempest/dummydetections:
  ros__parameters:
    topic: detected_objects
    timer_rate: 0.1
    detection_data:
      gman:
        pose: [0.0, 0.0, -0.25, 0.0, 0.0, -3.1415]
        noise: 0.1
        score: 0.8
      bootlegger:
        pose: [0.0, -1.0, -0.25, 0.0, 0.0, -3.1415]
        noise: 0.1
        score: 0.8
