/tempest/dummydetections:
  ros__parameters:
    topic: detected_objects
    timer_rate: 0.1
    detection_data:
      gman:
        pose: [1.5, -1.0, -0.25, 0.0, 0.0, 1.2]
        noise: 0.1
        score: 0.8
      bootlegger:
        pose: [0.5, -0.75, -0.25, 0.0, 0.0, 1.8]
        noise: 0.1
        score: 0.8
