/tempest/dummydetections:
  ros__parameters:
    topic: detected_objects
    timer_rate: 0.1
    detection_data:
      gman:
        pose: [0.75, 0.24, -0.25, 0.0, 0.0, 3.3]
        noise: 0.1
        score: 0.8
      bootlegger:
        pose: [0.5, 0.5, -0.25, 0.0, 0.0, 3.0]
        noise: 0.1
        score: 0.8
