/**/dummydetections:
  ros__parameters:
    timer_period: 0.05
    objects:
      - gate #gate
      - gate_repair
      - gate_rescue
      - slalom_front #slalom
      - slalom_middle
      - slalom_back
      - torpedo # torps
      - blood_hole_large
      - blood_hole_small
      - fire_hole_large
      - fire_hole_small
      - bin_target #bin
      - bin_target1
      - bin_target2
      - table #table
      - helmet
      - warning
      - pill
      - plug
      - nut_and_bolt
      - bandage
      - compass #octagon
    detection_data:
      gate:
        pose: [2.0, 0.0, -0.8, 0.0, 0.0, 0.0]
        noise: 0.001
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5 #meters. if simulate_pool is true, object will not be published if the robot is closer to the object than this value
        max_dist: 4.5 #meters. if simulate_pool is true, object will not be published if the robot is farther from the object than this value
      gate_repair:
        pose: [2.0, 0.5, -0.8, 0.0, 0.0, 3.1415]
        noise: 0.001
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.25
        max_dist: 3.5
      gate_rescue:
        pose: [2.0, -0.5, -0.8, 0.0, 0.0, 3.1415]
        noise: 0.001
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.25
        max_dist: 3.5
      slalom_front:
        pose: [4.5, 0.0, -2.25, 0.0, 0.0, 3.1415]
        noise: 0.1
        score: 0.8
        downward: false
        pub_invalid_orientation: true
        min_dist: 0.5
        max_dist: 3.0
      slalom_middle:
        pose: [6.5, 1.0, -2.25, 0.0, 0.0, 3.1415]
        noise: 0.1
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      slalom_back:
        pose: [8.5, 0.0, -2.25, 0.0, 0.0, 3.1415]
        noise: 0.1
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      torpedo:
        pose: [12.0, 4.0, -3.0, 0.0, 0.0, 3.1415]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 1.0
        max_dist: 3.5
      blood_hole_large:
        pose: [12.0, -3.970028, -2.782576, 0.0, 0.0, 3.1415]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      blood_hole_small:
        pose: [12.0, -3.970028, -3.0889, 0.0, 0.0, 3.1415]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      fire_hole_large:
        pose: [12.0, 4.11176, -3.0889, 0.0, 0.0, 3.1415]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      fire_hole_small:
        pose: [12.0, 4.11176, -2.782576, 0.0, 0.0, 3.1415]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      bin_target:
        pose: [11.0, -6.0, -3.25, 0.0, 0.0, 0.0]
        noise: 0.05
        score: 0.8
        downward: true
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      bin_target1:
        class_id: blood
        pose: [4.0, -3.0, -3.25, 0.0, 0.0, 0.0]
        noise: 0.05
        score: 0.8
        downward: true
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      bin_target2:
        class_id: blood
        pose: [4.7, -3.5, -3.25, 0.0, 0.0, 0.0]
        noise: 0.05
        score: 0.8
        downward: true
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
      table:
        pose: [4.0, 8.0, -3.25, 0.0, 0.0, 0.0]
        noise: 0.05
        score: 0.8
        downward: true
        pub_invalid_orientation: false
        min_dist: 1.0
        max_dist: 4.0
      helmet:
        pose: [9.5, 4.0, -0.8, 0.0, 0.0, 0.0]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.12
        max_dist: 3.0
      warning:
        pose: [10.5, 4.0, -0.8, 0.0, 0.0, 3.1415]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.12
        max_dist: 3.0
      pill:
        pose: [0.35, 0.0, -2.0, 0.0, -1.5707, 0.0]
        noise: 0.05
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.01
        max_dist: 4.0
      plug:
        pose: [-0.35, 0.0, -2.0, 0.0, -1.5707, 0.0]
        noise: 0.05
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.01
        max_dist: 4.0
      nut_and_bolt:
        pose: [0.2, 0.3, -2.0, 0.0, -1.5707, 0.0]
        noise: 0.05
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.01
        max_dist: 4.0
      bandage:
        pose: [-0.2, -0.3, -2.0, 0.0, -1.5707, 0.0]
        noise: 0.05
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.01
        max_dist: 4.0
      compass:
        pose: [10.5, 4.0, -0.8, 0.0, 0.0, 3.1415]
        noise: 0.01
        score: 0.8
        downward: false
        pub_invalid_orientation: false
        min_dist: 0.5
        max_dist: 3.0
  
/talos/dummydetections:
  ros__parameters:
    #POOL SIMULATION SETTINGS
    simulate_pool: true #if true, will monitor robot's odometry and only publish a detection for an object if the robot is looking at it
    
    #the following settings are only used when simulate_pool is TRUE
    forward_camera_frame: <robot>/base_link #if <robot> is present in name, it will be populated with the robot name
    forward_camera_pub_frame: <robot>/base_link # this is the frame that the detections are published in
    forward_camera_hfov: 120 #degrees. used to determine if robot is actually looking at the object.
    forward_camera_vfov: 68 #degrees. used just like the hfov but not horizontal
    
    downward_camera_frame: <robot>/dfc_camera_link #if <robot> is present in name, it will be populated with the robot name
    downward_camera_pub_frame: <robot>/dfc_camera_link
    downward_camera_hfov: 60
    downward_camera_vfov: 40

/liltank/dummydetections:
  ros__parameters:
    #POOL SIMULATION SETTINGS
    simulate_pool: true #if true, will monitor robot's odometry and only publish a detection for an object if the robot is looking at it
    
    #the following settings are only used when simulate_pool is TRUE
    forward_camera_frame: simulator/<robot>/zed2i/left_optical #if <robot> is present in name, it will be populated with the robot name
    forward_camera_pub_frame: <robot>/base_link # this is the frame that the detections are published in
    forward_camera_hfov: 60 #degrees. used to determine if robot is actually looking at the object.
    forward_camera_vfov: 120 #degrees. used just like the hfov but not horizontal
    
    downward_camera_frame: <robot>/dummy_dfc_link #if <robot> is present in name, it will be populated with the robot name
    downward_camera_pub_frame: <robot>/base_link
    downward_camera_hfov: 60
    downward_camera_vfov: 40
  
